# Generated by Django 5.0

from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("terminated", "Terminated")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("party", models.ForeignKey(on_delete=CASCADE, related_name="contracts", to="parties.party")),
                ("unit", models.ForeignKey(on_delete=CASCADE, related_name="contracts", to="properties.unit")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
